In [1]:
import os
from dotenv import load_dotenv
from supabase import create_client
import json
load_dotenv()

# ── supabase ──────────────────────────────────────────────────────────────────
_hf_token      = os.getenv("HF_TOKEN")
_supabase_url  = os.getenv("url")
_supabase_key  = os.getenv("key")

import os

url = os.getenv("url")
key = os.getenv("key")
supabase = create_client(url, key)

from smolagents import CodeAgent, InferenceClientModel, OpenAIModel, tool
import ast
@tool
def query_database(sql: str) -> str:
    """
    Query the PC components database to get prices, benchmarks and compatibility info.
    Args:
        sql: SQL SELECT query to execute (no semicolons).
    """
    try:
        clean_sql = sql.strip().rstrip(";")
        response = supabase.rpc("run_query", {"sql": clean_sql}).execute()
        return json.dumps(response.data, ensure_ascii=False, indent=2) if response.data else "[]"
    except Exception as e:
        return f"Database Error: {e}"

# ── helpers ───────────────────────────────────────────────────────────────────
def get_available_tests() -> list[str]:
    try:
        response = supabase.rpc("run_query", {"sql": "SELECT distinct(test) FROM model_x_test"}).execute()
        return [row["test"] for row in response.data] if response.data else []
    except Exception:
        return ["Relative Performance TechPowerUp"]

def _parse_agent_output(raw) -> dict | str:
    """Пробует привести ответ агента к dict; если не выходит — возвращает как есть."""
    if isinstance(raw, dict):
        return raw
    clean = str(raw).replace("Final answer:", "").strip()
    try:
        return ast.literal_eval(clean)
    except (ValueError, SyntaxError):
        return clean

# ── model / agent factories ───────────────────────────────────────────────────
def make_model(provider: str):
    match provider:
        case "hf" | "huggingface":
            return InferenceClientModel(
                model_id="meta-llama/Llama-4-Scout-17B-16E-Instruct",
                token=_hf_token,
            )
        case "groq":
            return OpenAIModel(
                model_id="llama-3.3-70b-versatile",
                api_base="https://api.groq.com/openai/v1",
                api_key=os.getenv("GROQ_API_KEY"),
            )
        case "google":
            return OpenAIModel(
                model_id="gemini-2.0-flash",
                api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
                api_key=os.getenv("GOOGLE_API_KEY"),
            )
        case _:
            raise ValueError(f"Неизвестный провайдер: {provider}")

def make_agent(model, sys_prompt: str, name: str, max_steps: int = 8) -> CodeAgent:
    return CodeAgent(
        tools=[query_database],
        model=model,
        code_block_tags=("```python", "```"),
        additional_authorized_imports=["json", "re", "pandas"],
        instructions=sys_prompt,
        max_steps=max_steps,
        verbosity_level=0,          # rich-вывод заглушён; логи идут в файл
    )

# бюджетные доли: [min, max] для каждого компонента
RATIO = {
    "GPU":      [0.38, 0.51],
    "CPU_MB":   [0.14, 0.22],
    "RAM":      [0.10, 0.16],
    "PSU":      [0.04, 0.08],
    "STORAGE":  [0.08, 0.16],
    "CASE":     [0.02, 0.06],
    "COOLER":   [0.01, 0.04],
}

if __name__ == "__main__":
    # ── main flow ─────────────────────────────────────────────────────────────────
    available_tests = get_available_tests()
    model_ll = make_model("hf")

C:\Users\ya\Documents\agent_try\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def query_database(sql: str) -> str:
    """
    Query the PC components database to get prices, benchmarks and compatibility info.
    Args:
        sql: SQL SELECT query to execute (no semicolons).
    """
    try:
        clean_sql = sql.strip().rstrip(";")
        response = supabase.rpc("run_query", {"sql": clean_sql}).execute()
        return json.dumps(response.data, ensure_ascii=False, indent=2) if response.data else "[]"
    except Exception as e:
        return f"Database Error: {e}"

response = query_database(
    """
    SELECT
    c.normalized_model_name AS cpu_name,
    t.test,
    t.result,
    c.tdp,
    CASE
        WHEN c.tdp < 70 THEN 'low'
        WHEN c.tdp >= 70 AND c.tdp < 121 THEN 'mid'
        ELSE 'high'
    END AS tdp_tier,
        c.socket,
        c.compatible_chipsets_no_bios_flash
    FROM cpu_x_test AS t
    INNER JOIN cpus AS c
        ON c.id = t.cpu_id
    ORDER BY
        c.normalized_model_name,
        t.test
    LIMIT 8000;
    """
)

In [3]:
converted_dict = json.loads(response) if response != "[]" else {}

In [4]:
response

'[\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 11500,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1480,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 401,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "PUBG",\n    "result": 145,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 84.6,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 11500,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1500,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 403,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Dragon\'s Dogma 2",\n    "result": 44.6,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "PUBG",\n    "result": 145,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 85,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 5 5600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 14100,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1830,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 14200,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1850,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 586,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 106,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Cinebench R23 Multi core",\n    "result": 14300,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Cinebench R23 Single core",\n    "result": 1910,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "CS2",\n    "result": 592,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Dragon\'s Dogma 2",\n    "result": 72.3,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 108,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 7600X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 16300,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1980,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 593,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Kingdom Come: Deliverance 2",\n    "result": 131,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "S.T.A.L.K.E.R. 2",\n    "result": 146,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Silent Hill f",\n    "result": 148,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "The Last of Us 2 Remastered",\n    "result": 155,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9500F",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 16300,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 2110,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 598,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 17037,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 2244,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 604,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cyberpunk 2077",\n    "result": 105,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Forza Horizon 5",\n    "result": 237,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Ghost of Tsushima",\n    "result": 184,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Hogwarts Legacy",\n    "result": 66,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Horizon Forbidden West",\n    "result": 157,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Kingdom Come: Deliverance 2",\n    "result": 138,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Microsoft Flight Simulator",\n    "result": 128,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Red Dead Redemption 2",\n    "result": 187,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Silent Hill f",\n    "result": 154,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Star Wars Outlaws",\n    "result": 115,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Starfield",\n    "result": 97,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "The Last of Us 2 Remastered",\n    "result": 164,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 107,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 5 9600X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "B840",\n      "B850",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 13800,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5700X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1520,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5700X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 84,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5700X",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Cinebench R23 Multi core",\n    "result": 15400,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Cinebench R23 Single core",\n    "result": 1590,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "CS2",\n    "result": 446,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Dragon\'s Dogma 2",\n    "result": 61.9,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 86,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A520",\n      "B550",\n      "X570"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "16 Game FPS Geomean",\n    "result": 126.8,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X3D",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": null\n  },\n  {\n    "tdp": 105,\n    "test": "CS2",\n    "result": 507,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X3D",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": null\n  },\n  {\n    "tdp": 105,\n    "test": "Dragon\'s Dogma 2",\n    "result": 72.1,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X3D",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": null\n  },\n  {\n    "tdp": 105,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 100,\n    "socket": "AM4",\n    "cpu_name": "AMD Ryzen 7 5800X3D",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": null\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Multi core",\n    "result": 18200,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Cinebench R23 Single core",\n    "result": 1920,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "CS2",\n    "result": 592,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 65,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 106,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700",\n    "tdp_tier": "low",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Cinebench R23 Multi core",\n    "result": 18200,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Cinebench R23 Single core",\n    "result": 1810,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "CS2",\n    "result": 597,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Dragon\'s Dogma 2",\n    "result": 75.5,\n    "socket": "AM5",\n    "cpu_name": "AMD Ryzen 7 7700X",\n    "tdp_tier": "mid",\n    "compatible_chipsets_no_bios_flash": [\n      "A620",\n      "B650",\n      "B650E",\n      "B840",\n      "B850",\n      "X670",\n      "X670E",\n      "X870",\n      "X870E"\n    ]\n  },\n  {\n    "tdp": 105,\n    "test": "Warhammer 40000: Space Marine 2",\n    "result": 109,\n    "socket": "AM5",\n  

In [17]:
def get_cpu_mb(min_p, max_p, ddr):
        tmp_sql = f"""
            WITH cpu_x_test_prices AS (
              SELECT
                c.normalized_model_name,
                t.test, t.result,
                p.price_rub,
                p.source_url,
                c.tdp,
                CASE
                    WHEN c.tdp < 70 THEN 'low'
                    WHEN c.tdp >= 70 AND c.tdp < 121 THEN 'mid'
                    ELSE 'high'
                END AS tdp_tier,
                c.socket,
                c.compatible_chipsets_no_bios_flash
              FROM cpu_x_test AS t
              INNER JOIN cpus AS c ON c.id = t.cpu_id
              INNER JOIN component_prices AS p
                  ON c.id = p.component_id
                 AND p.is_available = TRUE
                 AND p.is_verified = TRUE
            ),
            motherboard_prices AS (
              SELECT
                m.normalized_name,
                m.socket,
                m.chipset,
                m.vrm_tier,
                m.form_factor,
                m.ram_type,
                m.num_ram_slots,
                m.cpu_power_pins,
                m.required_cpu_power_pins,
                p.price_rub AS mb_price,
                p.source_url
              FROM motherboards AS m
              INNER JOIN component_prices AS p
                  ON m.id = p.component_id
                 AND p.is_available = TRUE
                 AND p.is_verified = TRUE
            )
            SELECT
              c.normalized_model_name AS cpu_name,
              m.normalized_name AS motherboard_name,
              c.test,
              c.result,
              c.price_rub + m.mb_price AS cpu_and_mb_price,
              c.tdp,
              m.form_factor,
              m.ram_type,
              m.num_ram_slots,
              m.cpu_power_pins,
              m.required_cpu_power_pins,
              m.source_url as motherboard_url,
              c.source_url as cpu_url
            FROM cpu_x_test_prices AS c
            INNER JOIN motherboard_prices AS m
                ON c.socket = m.socket
               AND m.chipset = ANY(c.compatible_chipsets_no_bios_flash)
               AND m.vrm_tier = c.tdp_tier
               AND m.ram_type = '{ddr}'
            WHERE (c.price_rub + m.mb_price) BETWEEN {min_p} AND {max_p}
            ORDER BY (c.price_rub + m.mb_price), cpu_name, motherboard_name, test
            """
        tmp_resp = supabase.rpc("run_query", {"sql": tmp_sql}).execute()
        return tmp_resp.data

get_cpu_mb(10000, 27000, 'DDR4')

[{'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 12400,
  'cpu_url': 'https://www.wildberries.ru/catalog/363133037/detail.aspx',
  'cpu_name': 'Intel Core i5-12400F',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171250137/detail.aspx',
  'cpu_and_mb_price': 14134,
  'motherboard_name': 'Gigabyte H610M K DDR4',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1710,
  'cpu_url': 'https://www.wildberries.ru/catalog/363133037/detail.aspx',
  'cpu_name': 'Intel Core i5-12400F',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171250137/detail.aspx',
  'cpu_and_mb_price': 14134,
  'motherboard_name': 'Gigabyte H610M K DDR4',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 134,
  'cpu_url': 'https://www.wildberries.ru/catalog/363133037/detail.aspx',
  'cpu_name': 'Intel Core i5-12400F',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171250137/detail.aspx',
  'cpu_and_mb_price': 14134,
  'motherboard_name': 'Gigabyte H610M K DDR4',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 90.0,
  'cpu_url': 'https://www.wildberries.ru/catalog/363133037/detail.aspx',
  'cpu_name': 'Intel Core i5-12400F',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171250137/detail.aspx',
  'cpu_and_mb_price': 14134,
  'motherboard_name': 'Gigabyte H610M K DDR4',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 14858,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1480,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 14858,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 401,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 14858,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 14858,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 84.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 14858,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15070,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1480,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15070,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 401,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15070,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15070,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 84.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15070,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 15583,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1480,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 15583,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 401,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 15583,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 15583,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 84.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 15583,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 15659,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1500,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 15659,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 403,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 15659,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': "Dragon's Dogma 2",
  'result': 44.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 15659,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 15659,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 85,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/171910127/detail.aspx',
  'cpu_and_mb_price': 15659,
  'motherboard_name': 'MSI A520M-A PRO',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15871,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1500,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15871,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 403,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15871,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': "Dragon's Dogma 2",
  'result': 44.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15871,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15871,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 85,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/223427674/detail.aspx',
  'cpu_and_mb_price': 15871,
  'motherboard_name': 'ASRock A520M-HVS',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 4,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/172675047/detail.aspx',
  'cpu_and_mb_price': 16317,
  'motherboard_name': 'Gigabyte B550M K',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1480,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 4,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/172675047/detail.aspx',
  'cpu_and_mb_price': 16317,
  'motherboard_name': 'Gigabyte B550M K',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 401,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 4,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/172675047/detail.aspx',
  'cpu_and_mb_price': 16317,
  'motherboard_name': 'Gigabyte B550M K',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 4,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/172675047/detail.aspx',
  'cpu_and_mb_price': 16317,
  'motherboard_name': 'Gigabyte B550M K',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 84.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 4,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/172675047/detail.aspx',
  'cpu_and_mb_price': 16317,
  'motherboard_name': 'Gigabyte B550M K',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 16384,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1500,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 16384,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 403,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 16384,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': "Dragon's Dogma 2",
  'result': 44.6,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 16384,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'PUBG',
  'result': 145,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 16384,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Warhammer 40000: Space Marine 2',
  'result': 85,
  'cpu_url': 'https://www.wildberries.ru/catalog/562016771/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600X',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 8,
  'motherboard_url': 'https://www.wildberries.ru/catalog/191274331/detail.aspx',
  'cpu_and_mb_price': 16384,
  'motherboard_name': 'Gigabyte A520M DS3H V2',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Multi core',
  'result': 11500,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/732500107/detail.aspx',
  'cpu_and_mb_price': 16769,
  'motherboard_name': 'ASRock B550M-HVS SE',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'Cinebench R23 Single core',
  'result': 1480,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,
  'cpu_power_pins': 4,
  'motherboard_url': 'https://www.wildberries.ru/catalog/732500107/detail.aspx',
  'cpu_and_mb_price': 16769,
  'motherboard_name': 'ASRock B550M-HVS SE',
  'required_cpu_power_pins': 4},
 {'tdp': 65,
  'test': 'CS2',
  'result': 401,
  'cpu_url': 'https://www.wildberries.ru/catalog/377609179/detail.aspx',
  'cpu_name': 'AMD Ryzen 5 5600',
  'ram_type': 'DDR4',
  'form_factor': 'mATX',
  'num_ram_slots': 2,

In [5]:
import pandas as pd
df = pd.DataFrame.from_dict(converted_dict)
df.drop(['socket', 'tdp', 'tdp_tier', 'compatible_chipsets_no_bios_flash'], axis=1, inplace=True)

In [6]:
df

                                test   result                  cpu_name
0           Cinebench R23 Multi core  11500.0          AMD Ryzen 5 5600
1          Cinebench R23 Single core   1480.0          AMD Ryzen 5 5600
2                                CS2    401.0          AMD Ryzen 5 5600
3                               PUBG    145.0          AMD Ryzen 5 5600
4    Warhammer 40000: Space Marine 2     84.6          AMD Ryzen 5 5600
..                               ...      ...                       ...
201        Cinebench R23 Single core   2280.0  Intel Core Ultra 7 265KF
202              16 Game FPS Geomean    142.0   Intel Core Ultra 9 285K
203         Cinebench R23 Multi core  41558.0   Intel Core Ultra 9 285K
204        Cinebench R23 Single core   2320.0   Intel Core Ultra 9 285K
205  Warhammer 40000: Space Marine 2    109.0   Intel Core Ultra 9 285K

[206 rows x 3 columns]

In [7]:
df_wide = df.pivot(
    index='cpu_name',
    columns='test',
    values='result'
).reset_index()

# Опционально: убираем имя индекса столбцов, чтобы таблица выглядела чистой
df_wide.columns.name = None

In [22]:
df_wide[['cpu_name', '16 Game FPS Geomean']]

                    cpu_name  16 Game FPS Geomean
0           AMD Ryzen 5 5600           115.136968
1          AMD Ryzen 5 5600X           130.884753
2          AMD Ryzen 5 7500F           141.061677
3           AMD Ryzen 5 7600           146.472100
4          AMD Ryzen 5 7600X           147.683831
5          AMD Ryzen 5 9500F           141.442043
6           AMD Ryzen 5 9600           143.321067
7          AMD Ryzen 5 9600X           154.092173
8          AMD Ryzen 7 5700X           117.467087
9          AMD Ryzen 7 5800X           127.605218
10       AMD Ryzen 7 5800X3D           126.800000
11          AMD Ryzen 7 7700           145.063367
12         AMD Ryzen 7 7700X           146.960173
13       AMD Ryzen 7 7800X3D           168.800000
14         AMD Ryzen 7 9700X           145.342116
15       AMD Ryzen 7 9800X3D           195.800000
16         AMD Ryzen 9 5900X           146.226646
17         AMD Ryzen 9 5950X           148.958231
18         AMD Ryzen 9 7900X           149.032029
19       AMD Ryzen 9 7900X3D           151.000000
20         AMD Ryzen 9 7950X           146.462833
21       AMD Ryzen 9 7950X3D           162.400000
22         AMD Ryzen 9 9900X           142.600000
23       AMD Ryzen 9 9900X3D           181.600000
24         AMD Ryzen 9 9950X           149.800000
25       AMD Ryzen 9 9950X3D           194.800000
26    Intel Core Ultra 5 225           141.631505
27   Intel Core Ultra 5 225F           141.631505
28   Intel Core Ultra 5 245K           131.800000
29  Intel Core Ultra 5 245KF           131.800000
30   Intel Core Ultra 7 265K           138.800000
31  Intel Core Ultra 7 265KF           138.800000
32   Intel Core Ultra 9 285K           142.000000
33       Intel Core i5-12400           117.796858
34      Intel Core i5-12400F           117.796858
35      Intel Core i5-13400F           131.820626
36       Intel Core i5-13500           144.073096
37      Intel Core i5-14400F           142.138016
38       Intel Core i5-14500           144.146261
39     Intel Core i5-14600KF           143.000000
40      Intel Core i7-12700F           144.059397
41      Intel Core i7-13700F           147.136621
42     Intel Core i7-13700KF           153.247794
43      Intel Core i7-14700F           148.039305
44     Intel Core i7-14700KF           149.800000
45     Intel Core i9-12900KF           146.300837
46     Intel Core i9-13900KF           150.526766
47     Intel Core i9-14900KF           154.200000

In [10]:
df_wide['Cinebench R23 Multi core'] = df_wide['Cinebench R23 Multi core']/100

In [11]:
df_wide['Cinebench R23 Single core'] = df_wide['Cinebench R23 Single core']/100

In [12]:
import pandas as pd
import numpy as np

# Обязательный импорт, без него IterativeImputer не заработает (он пока в режиме experimental)
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# --- ШАГ 1: Разделяем метаданные и тесты ---
# Составляем список всех нечисловых столбцов, которые у тебя есть в df_wide
metadata_columns = ['cpu_name', 'tdp', 'tdp_tier', 'socket', 'compatible_chipsets_no_bios_flash']

# Отбираем только те столбцы, которые являются тестами (все остальные)
test_columns = [col for col in df_wide.columns if col not in metadata_columns]

# --- ШАГ 2: Настраиваем и запускаем MICE ---
# max_iter=10 — это количество циклов пересчета (цепочек), 10 обычно за глаза
# random_state=42 — фиксируем сид, чтобы при каждом запуске пропуски заполнялись одинаково
imputer = IterativeImputer(max_iter=10, random_state=42)

# Обучаем импутер и трансформируем только числовую матрицу тестов
# На выходе получаем обычный numpy-массив без названий столбцов
imputed_data = imputer.fit_transform(df_wide[test_columns])

# --- ШАГ 3: Возвращаем данные обратно в DataFrame ---
# Просто перезаписываем столбцы тестов обновленными данными без пропусков
df_wide[test_columns] = imputed_data

In [13]:
df_wide

,cpu_name,16 Game FPS Geomean,CS2,Cinebench R23 Multi core,Cinebench R23 Single core,Cyberpunk 2077,Dragon's Dogma 2,Forza Horizon 5,Ghost of Tsushima,Hogwarts Legacy,...,Kingdom Come: Deliverance 2,Microsoft Flight Simulator,PUBG,Red Dead Redemption 2,S.T.A.L.K.E.R. 2,Silent Hill f,Star Wars Outlaws,Starfield,The Last of Us 2 Remastered,Warhammer 40000: Space Marine 2
0,AMD Ryzen 5 5600,115.136968,401.000000,115.000000,14.800000,102.628115,51.393911,219.210552,163.838256,74.301923,...,71.214149,117.325441,145.000000,170.395918,146.0,96.754763,129.232166,115.976405,78.131778,84.600000
1,AMD Ryzen 5 5600X,130.884753,403.000000,115.000000,15.000000,102.731670,44.600000,219.987233,164.718518,73.939460,...,75.308296,117.791506,145.000000,171.120858,146.0,100.264028,128.610782,115.147882,83.395669,85.000000
2,AMD Ryzen 5 7500F,141.061677,566.444219,141.000000,18.300000,104.743747,69.253456,235.078013,181.821638,66.896981,...,121.199298,126.846544,183.173584,185.205968,146.0,139.599424,116.537770,99.050414,142.399161,103.096510
3,AMD Ryzen 5 7600,146.472100,586.000000,142.000000,18.500000,105.032896,71.270660,237.246659,184.279470,65.884930,...,127.484835,128.147810,188.653002,187.230091,146.0,144.987068,114.802799,96.737103,150.480693,106.000000
4,AMD Ryzen 5 7600X,147.683831,592.000000,143.000000,19.100000,105.112801,72.300000,237.845960,184.958688,65.605251,...,129.446264,128.507416,190.417013,187.789456,146.0,146.668302,114.323341,96.097821,153.002559,108.000000
5,AMD Ryzen 5 9500F,141.442043,593.000000,163.000000,19.800000,104.863914,72.881894,235.979322,182.843187,66.476338,...,131.000000,127.387485,193.038643,186.047295,146.0,148.000000,115.816616,98.088844,155.000000,106.717006
6,AMD Ryzen 5 9600,143.321067,598.000000,163.000000,21.100000,104.943909,73.396276,236.579293,183.523163,66.196348,...,132.757314,127.747489,194.439391,186.607282,146.0,149.506279,115.336625,97.448851,157.259435,107.444546
7,AMD Ryzen 5 9600X,154.092173,604.000000,170.370000,22.440000,105.000000,74.336609,237.000000,184.000000,66.000000,...,138.000000,128.000000,197.483403,187.000000,146.0,154.000000,115.000000,97.000000,164.000000,107.000000
8,AMD Ryzen 7 5700X,117.467087,461.428956,138.000000,15.200000,103.189207,58.506453,223.418829,168.607734,72.338012,...,89.006401,119.850641,154.276843,174.323800,146.0,112.005285,125.865384,111.487315,101.007597,84.000000
9,AMD Ryzen 7 5800X,127.605218,446.000000,154.000000,15.900000,102.853890,61.900000,220.903967,165.757582,73.511602,...,90.187681,118.341786,152.884285,171.976637,146.0,113.017726,127.877232,114.169765,102.526135,86.000000
10,AMD Ryzen 7 5800X3D,126.800000,507.000000,308.460565,21.742200,101.938810,72.100000,214.041116,157.979987,76.714119,...,127.118279,114.224805,189.316541,165.571798,146.0,144.672070,133.367015,121.489326,150.007024,100.000000
11,AMD Ryzen 7 7700,145.063367,592.000000,182.000000,19.200000,104.651790,73.598705,234.388420,181.040198,67.218743,...,134.312918,126.433024,195.458870,184.562507,146.0,150.839573,117.089283,99.785716,159.259258,106.000000
12,AMD Ryzen 7 7700X,146.960173,597.000000,182.000000,18.100000,104.734004,75.500000,235.005035,181.739037,66.930985,...,136.006426,126.803015,196.853883,185.138029,146.0,152.291165,116.595976,99.127969,161.436665,109.000000
13,AMD Ryzen 7 7800X3D,168.800000,722.000000,185.500000,18.100000,106.574492,86.000000,248.808861,197.383569,60.489104,...,173.770305,135.085780,246.000000,198.021916,146.0,184.660494,105.552594,84.403362,209.991131,125.000000
14,AMD Ryzen 7 9700X,145.342116,605.000000,212.000000,21.800000,104.492641,76.217818,233.194854,179.687551,67.775711,...,141.959417,125.717032,202.861971,183.448611,146.0,157.393628,118.044035,101.058689,169.090222,108.000000
15,AMD Ryzen 7 9800X3D,195.800000,793.619310,228.000000,20.300000,107.186578,95.968821,253.399646,202.586628,58.346655,...,202.344075,137.840660,250.000000,202.306923,146.0,209.152254,101.879687,79.506068,246.728713,138.000000
16,AMD Ryzen 9 5900X,146.226646,548.583525,225.000000,16.100000,103.568273,71.080247,226.262054,171.830334,71.011039,...,129.941193,121.557248,189.922813,176.977927,146.0,147.092128,123.590346,108.453792,153.637720,105.626782
17,AMD Ryzen 9 5950X,148.958231,540.408741,286.000000,16.300000,102.776250,72.899911,220.321947,165.098301,73.783045,...,137.302311,117.993397,196.038942,171.433970,146.0,153.401413,128.342287,114.789668,163.101299,107.807986
18,AMD Ryzen 9 7900X,149.032029,558.196844,294.000000,20.330000,102.934564,75.063750,221.509334,166.444039,73.228915,...,143.026432,118.705909,201.775651,172.542251,146.0,158.307808,127.392323,113.523033,170.460905,111.000000
19,AMD Ryzen 9 7900X3D,151.000000,562.833950,279.070000,19.070000,103.178718,74.878165,223.340477,168.519321,72.374389,...,142.462699,119.804560,201.078286,174.251295,146.0,157.824676,125.927432,111.569853,169.736305,111.000000
20,AMD Ryzen 9 7950X,146.462833,520.342248,387.270000,20.500000,101.335712,75.288762,209.518014,152.853972,78.824818,...,146.391926,111.511347,204.211314,161.350507,146.0,161.192085,136.985222,126.313518,174.786697,111.000000
21,AMD Ryzen 9 7950X3D,162.400000,563.287246,357.700000,20.610000,102.350016,78.339194,217.125322,161.475618,75.274726,...,156.638624,116.075803,212.179593,168.450709,146.0,169.975180,130.899327,118.198976,187.961651,112.000000
22,AMD Ryzen 9 9900X,142.600000,539.977504,335.000000,22.100000,102.183287,75.012818,215.874779,160.058243,75.858358,...,142.901107,115.325253,202.211378,167.283385,146.0,158.200190,131.899914,119.533139,170.299192,112.000000
23,AMD Ryzen 9 9900X3D,181.600000,709.155888,335.000000,22.100000,104.741684,92.033534,235.062974,181.805121,66.903742,...,194.238678,126.838791,251.000000,185.192784,146.0,202.204212,116.548935,99.065038,236.305838,130.643131
24,AMD Ryzen 9 9950X,149.800000,531.909710,421.020000,22.430000,101.131829,77.929669,207.988953,151.121107,79.538345,...,154.957000,110.594081,211.889442,159.923498,146.0,168.533476,138.208355,127.944326,185.798644,115.000000
25,AMD Ryzen 9 9950X3D,194.800000,727.067403,421.030000,22.430000,104.050320,97.675695,229.877879,175.928838,69.323376,...,212.806635,123.728115,252.000000,180.353617,146.0,218.119295,120.696751,104.595381,260.178013,137.921914
26,Intel Core Ultra 5 225,141.631505,566.145026,172.060000,19.850000,104.390084,70.577207,232.425582,178.815598,68.134758,...,125.763377,125.255202,187.266523,182.730444,146.0,143.511374,118.659635,101.879544,148.266920,104.484058
27,Intel Core Ultra 5 225F,141.631505,566.145026,172.060000,19.850000,104.390084,70.577207,232.425582,178.815598,68.134758,...,125.763377,125.255202,187.266523,182.730444,146.0,143.511374,118.659635,101.879544,148.266920,104.484058
28,Intel Core Ultra 5 245K,131.800000,532.000000,248.000000,22.100000,103.000000,70.427342,222.000000,167.000000,73.000000,...,125.867475,119.000000,188.029786,173.000000,146.0,143.600235,127.000000,113.000000,148.399683,102.000000
29,Intel Core Ultra 5 245KF,131.800000,532.000000,248.000000,22.100000,103.000000,70.427342,222.000000,167.000000,73.000000,...,125.867477,119.000000,188.029788,173.000000,146.0,143.600236,127.000000,113.000000,148.399684,102.000000
30,Intel Core Ultra 7 265K,138.800000,520.209859,351.000000,22.800000,101.704687,73.711167,212.285278,155.990137,77.533461,...,139.409221,113.171542,199.004266,163.933177,146.0,155.207039,134.771522,123.361952,165.809308,107.355313
31,Intel Core Ultra 7 265KF,138.800000,520.209859,351.000000,22.800000,101.704687,73.711167,212.285278,155.990137,77.533461,...,139.409221,113.171542,199.004266,163.933177,146.0,155.207039,134.771522,123.361952,165.809308,107.355313
32,Intel Core Ultra 9 285K,142.000000,504.922352,415.580000,23.200000,100.776053,74.973280,205.320587,148.096907,80.783608,...,145.664340,108.992937,203.769641,157.432939,146.0,160.568296,140.343132,130.790722,173.850803,109.000000
33,Intel Core i5-12400,117.796858,433.857918,124.000000,17.100000,102.953533,55.245506,221.651217,166.604378,73.162928,...,79.537019,118.789925,134.000000,172.673929,146.0,103.888642,127.279575,113.372933,88.832572,90.000000
34,Intel Core i5-12400F,117.796858,433.857918,124.000000,17.100000,102.953533,55.245506,221.651217,166.604378,73.162928,...,79.537019,118.789925,134.000000,172.673929,146.0,103.888642,127.279575,113.372933,88.832572,90.000000
35,Intel Core i5-13400F,131.820626,458.954765,133.779199,16.382023,103.271628,57.400000,224.036988,169.308322,72.049535,...,90.861047,120.221556,147.000000,174.900761,146.0,113.594982,125.370844,110.827924,103.392138,91.079274
36,Intel Core i5-13500,144.073096,557.412879,208.000000,18.500000,103.873145,71.246707,228.548578,174.421709,69.944003,...,129.273377,122.929117,189.878003,179.111986,146.0,146.519794,121.761158,106.014884,152.779333,105.488497
37,Intel Core i5-14400F,142.138016,562.683468,158.000000,17.800000,104.503977,69.608143,233.279758,179.783639,67.736155,...,122.937637,125.767647,184.502489,183.527635,146.0,141.089357,117.976335,100.968490,144.633960,103.598117
38,Intel Core i5-14500,144.146261,557.375379,212.000000,18.700000,103.827613,71.417290,228.207089,174.034695,70.103361,...,129.861370,122.724238,190.405366,178.793273,146.0,147.023773,122.034339,106.379122,153.535281,105.667263
39,Intel Core i5-14600KF,143.000000,534.000000,245.000000,20.100000,103.128570,73.800000,222.964290,168.092879,72.549990,...,128.733005,119.578615,188.691069,173.900032,146.0,146.056431,126.228540,111.971378,152.084016,108.000000
40,Intel Core i7-12700F,144.059397,558.014175,215.000000,19.100000,103.802029,71.613799,228.015219,173.817247,70.192899,...,130.443223,122.609129,190.969847,178.614202,146.0,147.522494,122.187827,106.583769,154.283348,105.849144
41,Intel Core i7-13700F,147.136621,549.611128,294.230000,20.190000,102.801755,74.204995,220.513252,165.315134,73.693759,...,140.472008,118.108230,199.474898,171.612555,146.0,156.118281,128.189208,114.585554,167.176583,108.840965
42,Intel Core i7-13700KF,153.247794,583.634660,305.070000,20.610000,103.189144,78.082470,223.418731,168.608079,72.337836,...,152.133752,119.851683,213.000000,174.324446,146.0,166.114109,125.864713,111.486192,182.170404,113.409682
43,Intel Core i7-14700F,148.039305,547.416748,321.000000,20.800000,102.472067,75.146800,218.040627,162.512865,74.847632,...,143.996694,116.624751,202.511920,169.304836,146.0,159.139336,130.167244,117.222914,171.708015,109.898054
44,Intel Core i7-14700KF,149.800000,550.322941,352.650000,21.600000,102.161931,78.300000,215.714649,159.876812,75.933061,...,149.716871,115.229297,207.554987,167.134012,146.0,164.042234,132.027935,119.703808,179.062206,110.000000
45,Intel Core i9-12900KF,146.300837,551.992290,274.000000,20.000000,103.060183,73.567601,222.451444,167.511722,72.789284,...,137.961091,119.271074,197.362967,173.421486,146.0,153.966147,126.638704,112.518229,163.948496,108.093943
46,Intel Core i9-13900KF,150.526766,541.387621,395.000000,22.500000,101.561187,77.754002,211.209118,154.770599,78.035615,...,153.747708,112.526112,210.916439,162.928939,146.0,167.497058,135.632269,124.509559,184.244187,112.822788
47,Intel Core i9-14900KF,154.200000,622.000000,425.970000,23.750000,102.363001,83.300000,217.222849,161.586315,75.229132,...,179.593922,116.134724,246.000000,168.542004,146.0,189.651052,130.821031,118.094498,217.475349,122.512550

In [24]:
test_name = '16 Game FPS Geomean'

In [25]:
df_wide[['cpu_name', test_name]]

                    cpu_name  16 Game FPS Geomean
0           AMD Ryzen 5 5600           115.136968
1          AMD Ryzen 5 5600X           130.884753
2          AMD Ryzen 5 7500F           141.061677
3           AMD Ryzen 5 7600           146.472100
4          AMD Ryzen 5 7600X           147.683831
5          AMD Ryzen 5 9500F           141.442043
6           AMD Ryzen 5 9600           143.321067
7          AMD Ryzen 5 9600X           154.092173
8          AMD Ryzen 7 5700X           117.467087
9          AMD Ryzen 7 5800X           127.605218
10       AMD Ryzen 7 5800X3D           126.800000
11          AMD Ryzen 7 7700           145.063367
12         AMD Ryzen 7 7700X           146.960173
13       AMD Ryzen 7 7800X3D           168.800000
14         AMD Ryzen 7 9700X           145.342116
15       AMD Ryzen 7 9800X3D           195.800000
16         AMD Ryzen 9 5900X           146.226646
17         AMD Ryzen 9 5950X           148.958231
18         AMD Ryzen 9 7900X           149.032029
19       AMD Ryzen 9 7900X3D           151.000000
20         AMD Ryzen 9 7950X           146.462833
21       AMD Ryzen 9 7950X3D           162.400000
22         AMD Ryzen 9 9900X           142.600000
23       AMD Ryzen 9 9900X3D           181.600000
24         AMD Ryzen 9 9950X           149.800000
25       AMD Ryzen 9 9950X3D           194.800000
26    Intel Core Ultra 5 225           141.631505
27   Intel Core Ultra 5 225F           141.631505
28   Intel Core Ultra 5 245K           131.800000
29  Intel Core Ultra 5 245KF           131.800000
30   Intel Core Ultra 7 265K           138.800000
31  Intel Core Ultra 7 265KF           138.800000
32   Intel Core Ultra 9 285K           142.000000
33       Intel Core i5-12400           117.796858
34      Intel Core i5-12400F           117.796858
35      Intel Core i5-13400F           131.820626
36       Intel Core i5-13500           144.073096
37      Intel Core i5-14400F           142.138016
38       Intel Core i5-14500           144.146261
39     Intel Core i5-14600KF           143.000000
40      Intel Core i7-12700F           144.059397
41      Intel Core i7-13700F           147.136621
42     Intel Core i7-13700KF           153.247794
43      Intel Core i7-14700F           148.039305
44     Intel Core i7-14700KF           149.800000
45     Intel Core i9-12900KF           146.300837
46     Intel Core i9-13900KF           150.526766
47     Intel Core i9-14900KF           154.200000

In [30]:
import networkx as nx
import pandas as pd

# 1. Задаем граф зависимостей (направленные ребра от слабых к сильным)
cpu_hierarchy_edges= [
    # Цепочка Intel
    ('Intel Core i5-12400F', 'Intel Core i5-13400F'),
    ('Intel Core i5-12400', 'Intel Core i5-13400'),
    ('Intel Core i5-12400F', 'Intel Core i5-13400'),
    ('Intel Core i5-12400', 'Intel Core i5-13400F'),
    ('Intel Core i5-13400F', 'Intel Core i5-14400F'),
    ('Intel Core i5-14400', 'Intel Core i5-13500'),
    ('Intel Core i5-13500', 'Intel Core i5-14500'),
    ('Intel Core i5-14500', 'Intel Core i5-14600K'),
    ('Intel Core i5-14600K', 'Intel Core i7-14700F'),
    ('Intel Core i7-14700F', 'Intel Core i7-14700KF'),
    ('Intel Core i7-14700KF', 'Intel Core i9-14900KF'),
    ('Intel Core Ultra 5 225', 'Intel Core Ultra 5 245K'),
    ('Intel Core Ultra 5 225F', 'Intel Core Ultra 5 245KF'),
    ('Intel Core Ultra 5 245K', 'Intel Core Ultra 7 265K'),
    ('Intel Core Ultra 5 245KF', 'Intel Core Ultra 7 265KF'),
    ('Intel Core Ultra 7 265K', 'Intel Core Ultra 9 285K'),
    ('Intel Core Ultra 7 265KF', 'Intel Core Ultra 9 285K'),

    # Пересекающиеся цепочки с AMD
    ('AMD Ryzen 5 5600', 'AMD Ryzen 5 5600X'),
    ('AMD Ryzen 5 5600X', 'AMD Ryzen 7 5700X'),
    ('AMD Ryzen 7 5700X', 'AMD Ryzen 7 5800X'),
    ('AMD Ryzen 7 5800X', 'AMD Ryzen 5 5800X3D'),
    ('AMD Ryzen 5 5600X', 'AMD Ryzen 5 7500F'),
    ('AMD Ryzen 5 7500F', 'AMD Ryzen 5 7600'),
    ('AMD Ryzen 5 7600', 'AMD Ryzen 5 7600X'),
    ('AMD Ryzen 5 7600', 'AMD Ryzen 7 7700'),
    ('AMD Ryzen 5 7600X', 'AMD Ryzen 7 7700X'),
    ('AMD Ryzen 5 7600', 'AMD Ryzen 5 9500F'),
    ('AMD Ryzen 5 9500F', 'AMD Ryzen 5 9600'),
    ('AMD Ryzen 5 9600', 'AMD Ryzen 5 9600X'),
    ('AMD Ryzen 5 9600X', 'AMD Ryzen 7 9700X'),
    ('AMD Ryzen 5 7600', 'AMD Ryzen 5 7600X'),
    ('AMD Ryzen 5 7600X', 'AMD Ryzen 9 9900X'),
    ('AMD Ryzen 7 7700X', 'AMD Ryzen 9 9950X'),
    ('AMD Ryzen 5 5600X', 'AMD Ryzen 9 7900X'),
    ('AMD Ryzen 7 5800X', 'AMD Ryzen 9 7950X'),

]
cpu_dag = nx.DiGraph(cpu_hierarchy_edges)
assert nx.is_directed_acyclic_graph(cpu_dag), "Критическая ошибка: в графе иерархии процессоров обнаружен цикл!"


class HierarchicalIterativeImputer:
    """
    Кастомный итеративный импутер, использующий циклическое дообучение моделей
    и коррекцию аномалий на основе направленного графа зависимостей (DAG).
    """
    def __init__(self, dag: nx.DiGraph, constrained_columns: list, max_iter=10, random_state=42):
        self.dag = dag
        self.constrained_columns = constrained_columns
        self.max_iter = max_iter
        self.random_state = random_state
        # Топологическая сортировка гарантирует обход от слабых к сильным
        self.topo_order = list(nx.topological_sort(dag))

    def _apply_constraints(self, df_indexed: pd.DataFrame, cols: list):
        """Применяет жесткие иерархические ограничения к колонкам из списка cols."""
        for col in cols:
            for node in self.topo_order:
                if node not in df_indexed.index:
                    continue

                # Ищем всех непосредственных предшественников (кто слабее текущего процессора)
                predecessors = [p for p in self.dag.predecessors(node) if p in df_indexed.index]

                if predecessors:
                    # Находим максимальный результат среди тех, кто заведомо слабее
                    max_pred_val = df_indexed.loc[predecessors, col].max()
                    current_val = df_indexed.at[node, col]

                    # Если более мощный процессор выдал результат меньше слабого — поднимаем его значение
                    if pd.notna(current_val) and pd.notna(max_pred_val) and current_val < max_pred_val:
                        # Принудительно устанавливаем значение на 1% выше максимального предшественника
                        df_indexed.at[node, col] = max_pred_val * 1.01

    def fit_transform(self, df: pd.DataFrame, test_columns: list, name_col='cpu_name') -> pd.DataFrame:
        df_res = df.copy()

        # 1. Первичное заполнение медианами для старта регрессионных моделей
        for col in test_columns:
            if df_res[col].isna().all():
                df_res[col] = df_res[col].fillna(0.0)
            else:
                df_res[col] = df_res[col].fillna(df_res[col].median())

        # Запоминаем маску, где изначально были NaN
        missing_mask = df[test_columns].isna()

        # Игры, на которые действуют правила графа
        game_cols = [c for c in test_columns if c in self.constrained_columns]

        # Индексируем для удобной работы с графом
        df_res_indexed = df_res.set_index(name_col)

        # Главный цикл чередующихся проекций
        for i in range(self.max_iter):
            # Шаг А: Регрессионная импутация для каждого теста
            for col in test_columns:
                other_cols = [c for c in test_columns if c != col]

                # Обучаемся только на строках, где изначально БЫЛИ реальные данные в базе
                train_idx = df[col].notna()

                if train_idx.sum() > 1: # Нужно хотя бы 2 примера для обучения
                    model = BayesianRidge()
                    X_train = df_res_indexed.loc[train_idx.values, other_cols]
                    y_train = df_res_indexed.loc[train_idx.values, col]

                    model.fit(X_train, y_train)

                    # Предсказываем значения только для тех позиций, где изначально стоял NaN
                    predict_idx = missing_mask[col].values
                    if predict_idx.sum() > 0:
                        X_pred = df_res_indexed.loc[predict_idx, other_cols]
                        predictions = model.predict(X_pred)
                        # Защита от отрицательных FPS/попугаев
                        predictions = np.clip(predictions, a_min=0, a_max=None)
                        df_res_indexed.loc[predict_idx, col] = predictions

            # Шаг Б: Коррекция аномалий по графу (на исправленных данных)
            self._apply_constraints(df_res_indexed, game_cols)

        return df_res_indexed.reset_index()


# -------------------------------------------------------------------------
# ОБНОВЛЕННАЯ ФУНКЦИЯ ЗАПРОСА С НОВЫМ ИМПУТЕРОМ
# -------------------------------------------------------------------------
def get_cpu_tests_pd(test_name: str | None, query_database_func, json_loads_func) -> pd.DataFrame:
    # Запрос данных из базы
    response = query_database_func(
        """
        SELECT
            c.normalized_model_name AS cpu_name,
            t.test,
            t.result
        FROM cpu_x_test AS t
        INNER JOIN cpus AS c
            ON c.id = t.cpu_id
        ORDER BY
            c.normalized_model_name,
            t.test
        LIMIT 8000;
        """
    )

    converted_dict = json_loads_func(response) if response != "[]" else {}
    df = pd.DataFrame.from_dict(converted_dict)

    # Разворачиваем таблицу в wide-формат
    df_wide = df.pivot(
        index='cpu_name',
        columns='test',
        values='result'
    ).reset_index()
    df_wide.columns.name = None

    # Нормализация Cinebench шкал
    if 'Cinebench R23 Multi core' in df_wide.columns:
        df_wide['Cinebench R23 Multi core'] = df_wide['Cinebench R23 Multi core'] / 100
    if 'Cinebench R23 Single core' in df_wide.columns:
        df_wide['Cinebench R23 Single core'] = df_wide['Cinebench R23 Single core'] / 100

    metadata_columns = ['cpu_name']
    test_columns = [col for col in df_wide.columns if col not in metadata_columns]

    # Исключаем синтетику из иерархических правил графа
    cinebench_cols = ['Cinebench R23 Multi core', 'Cinebench R23 Single core']
    constrained_cols = [col for col in test_columns if col not in cinebench_cols]

    # Создаем и запускаем наш кастомный иерархический импутер
    imputer = HierarchicalIterativeImputer(
        dag=cpu_dag,
        constrained_columns=constrained_cols,
        max_iter=10,
        random_state=42
    )

    df_wide = imputer.fit_transform(df_wide, test_columns, name_col='cpu_name')

    if test_name and test_name in df_wide.columns:
        return df_wide[['cpu_name', test_name]]

    return df_wide

In [31]:
print(get_cpu_tests_pd(test_name))

TypeError: get_cpu_tests_pd() missing 2 required positional arguments: 'query_database_func' and 'json_loads_func'